config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all.order(id: :asc)
    @todo ||= Todo.new
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to todos_path, notice: 'Todo was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:completed, :description, :timestamps)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui top borderless secondary pointing menu">
      <div class="active green item">
        <h1>TodoTracker</h1>
      </div>
    </div>  
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true, class: 'ui form') do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, data: { reflex: "input->ExampleReflex#form" } %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'ui green button' %>
    <%= link_to 'Back', todos_path, class: 'ui button' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<div class="ui padded grid">
  <div class="row">
    <div class="column">
      <% if notice.present? %>  
        <div class="ui positive message">
          <i class="close icon" data-controller="message" data-action="click->message#close"></i>
          <div class="header">
            <%= notice %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <h1>Todos</h1>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <%= render 'form', todo: @todo %>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <table class="ui celled table">
        <thead>
          <tr>
            <th>Completed</th>
            <th>Description</th>
            <th>Last Update</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @todos.each do |todo| %>
            <tr>
              <td><%= check_box_tag :done, 'true', todo.completed, class: 'ui checkbox', data: { reflex: 'click->ExampleReflex#toggle', id: todo.id} %></td>
              <td><%= todo.description %></td>
              <td><%= todo.updated_at %></td>
              <td><%= link_to 'Show', todo %></td>
              <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
              <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="column">
      <%= link_to 'New Todo', new_todo_path, class: 'ui green button' %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="ui grid">
    <div class="row">
        <h1>New Todo</h1>
    </div>
    <div class="row">
        <div class="column">
            <%= render 'form', todo: @todo %>
        </div>
    </div>
</div>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Timestamps:</strong>
  <%= @todo.timestamps %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>